---
- name: Installation et configuration d'Apache
  hosts: webservers
  become: yes
  serial: 1
  tasks:
    - name: Installation du paquet apache2
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Copier le fichier index.html personnalisé
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
